README updated with new namespace, poetry cmds
TrustTheVote-Project/VersaEDM-Backend pull request #7
Opened 2021-12-06 17:02 UTC by stratofax

README.md now includes:

- Version requirement: Python 3.9 or greater
- The new VersaDM naming convention
- A brief section on using `poetry` for package management
- Updated Docker commands for `versadm`

I also included the `poetry.lock` file I generated when I executed `poetry install`.

2021-12-06 21:41 UTC, ion-oset commented on README.md
> +poetry install
Add a note about using `poetry shell` to activate the environment `install` creates.

2021-12-07 02:37 UTC, stratofax commented on README.md
> +poetry install
Updated as suggested, thanks Ion!

2021-12-07 04:57 UTC, alanyst approved these changes

2021-12-07 05:46 UTC, alanyst requested changes
On reflection, I think we should omit `poetry.lock` from the repo and add it to .gitignore, since it can be generated on demand and is more like a build artifact than a source file.

2021-12-07 16:54 UTC, stratofax commented
Agreed, so I removed `poetry.lock` from this PR.

2021-12-07 16:55 UTC, stratofax commented
Agree with Alan, `poetry.lock` removed from this PR.

2021-12-07 17:54 UTC, alanyst approved these changes

2021-12-07 17:54 UTC, merged